# Generated by Django 4.2 on 2023-05-19 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopcion',
            name='edad',
        ),
        migrations.AddField(
            model_name='adopcion',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
