# Generated by Django 4.2 on 2023-05-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdidaBusqueda', '0002_alter_perro_perdido_estado_alter_perro_perdido_sexo_and_more'),
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='estado',
            field=models.CharField(choices=[('0', 'En adopción'), ('1', 'Adoptado')], max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='sexo',
            field=models.CharField(choices=[('0', 'Hembra'), ('1', 'Macho'), ('2', 'Ns/Nc')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='tamaño',
            field=models.CharField(choices=[('0', 'Chico: entre 3 y 10 kilos'), ('1', 'Mediano: entre 10 y 25 kilos'), ('2', 'Grande: entre 25 y 50 kilos'), ('3', 'Gigante: más de 50 kilos')], max_length=1, verbose_name='Tamaño'),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Sexo',
        ),
        migrations.DeleteModel(
            name='Tamaño',
        ),
    ]
