# Generated by Django 4.2 on 2023-05-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_alter_adopcion_estado_alter_adopcion_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
