# Generated by Django 4.1.7 on 2023-05-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_alter_cuenta_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='dni',
            field=models.CharField(max_length=10, verbose_name='DNI'),
        ),
    ]
