# Generated by Django 4.2 on 2023-05-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_cuenta_descuento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='descuento',
            new_name='es_donante',
        ),
    ]
