# Generated by Django 4.1.7 on 2023-06-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_rename_descuento_cuenta_es_donante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='descuento_acumulado',
            field=models.IntegerField(default=0),
        ),
    ]
