<<<<<<< HEAD
# Generated by Django 4.2 on 2023-06-11 23:18
=======
# Generated by Django 4.1.7 on 2023-06-11 21:32
>>>>>>> d4aaea2245c756ca9075ca758762a1c43cd94c30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_rename_descuento_cuenta_es_donante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='descuento_acumulado',
            field=models.IntegerField(default=0),
        ),
    ]
