# Generated by Django 4.2 on 2023-06-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_alter_cuenta_descuento_acumulado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='descuento_acumulado',
            field=models.IntegerField(default=0),
        ),
    ]
