# Generated by Django 4.2 on 2023-05-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
