# Generated by Django 4.2 on 2023-05-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0002_alter_donacion_created_alter_donacion_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donacion',
            options={'verbose_name': 'motivo', 'verbose_name_plural': 'motivos'},
        ),
    ]
