# Generated by Django 4.1.7 on 2023-05-31 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0003_tarjeta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
