# Generated by Django 4.1.7 on 2023-06-01 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0005_donacion_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donacion',
            options={'verbose_name': 'Donacion', 'verbose_name_plural': 'Donaciones'},
        ),
    ]
