# Generated by Django 4.1.7 on 2023-06-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0009_donacion_finalizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonanteNoRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, default=None, max_digits=8)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
