# Generated by Django 4.1.7 on 2023-06-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0011_alter_donante_monto_alter_donantenoregistrado_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='monto',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='donantenoregistrado',
            name='monto',
            field=models.IntegerField(default=None),
        ),
    ]
