# Generated by Django 4.2 on 2023-06-07 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0012_alter_donante_monto_alter_donantenoregistrado_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='donante',
            name='campaña',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donacion.donacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donantenoregistrado',
            name='campaña',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donacion.donacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
