# Generated by Django 4.1.7 on 2023-06-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0015_donante_campania_donacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('nombre_dueño', models.CharField(max_length=50)),
                ('saldo', models.IntegerField(default=None)),
                ('codigo_seguridad', models.CharField(max_length=3)),
                ('vencimiento', models.DateField()),
            ],
        ),
    ]
