# Generated by Django 4.1.7 on 2023-07-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0016_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='vencimiento',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='año_vencimiento',
            field=models.CharField(default=11, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='mes_vencimiento',
            field=models.CharField(default=11, max_length=2),
            preserve_default=False,
        ),
    ]
