# Generated by Django 4.1.7 on 2023-07-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0017_remove_tarjeta_vencimiento_tarjeta_año_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='año_vencimiento',
            field=models.CharField(max_length=4),
        ),
    ]
