# Generated by Django 4.2 on 2023-05-06 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='perro_perdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=20)),
                ('comentario', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(upload_to='')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perdidaBusqueda.estado')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.sexo')),
                ('tamaño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.tamaño')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perdidaBusqueda.zona')),
            ],
        ),
    ]
