# Generated by Django 4.1.7 on 2023-05-13 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='perro_perdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('0', 'Buscando dueño'), ('1', 'Buscando perro'), ('2', 'Reunidos')], max_length=1, verbose_name='Estado')),
                ('tamaño', models.CharField(choices=[('0', 'Chico: entre 3 y 10 kilos'), ('1', 'Mediano: entre 10 y 25 kilos'), ('2', 'Grande: entre 25 y 50 kilos'), ('3', 'Gigante: más de 50 kilos')], max_length=1, verbose_name='Tamaño')),
                ('sexo', models.CharField(choices=[('0', 'Hembra'), ('1', 'Macho'), ('2', 'Ns/Nc')], max_length=1, verbose_name='Sexo')),
                ('comentario', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.raza')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perdidaBusqueda.zona')),
            ],
        ),
    ]
