# Generated by Django 4.1.7 on 2023-06-25 16:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perdidaBusqueda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerroPerdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perrosPerdidos')),
                ('fecha_perdido', models.DateField(default=datetime.date.today)),
                ('fecha_nacimiento', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('0', 'Buscando dueño'), ('1', 'Buscando perro'), ('2', 'Reunidos')], max_length=1, verbose_name='Estado')),
                ('tamaño', models.CharField(choices=[('0', 'Chico: entre 3 y 10 kilos'), ('1', 'Mediano: entre 10 y 25 kilos'), ('2', 'Grande: entre 25 y 50 kilos'), ('3', 'Gigante: más de 50 kilos')], max_length=1, verbose_name='Tamaño')),
                ('raza', models.CharField(choices=[('0', 'Cruza'), ('1', 'Labrador'), ('2', 'Rottweiler'), ('3', 'Pug'), ('4', 'Chihuahua'), ('5', 'Husky Siberiano'), ('6', 'Golden'), ('7', 'Caniche'), ('8', 'Pastor Aleman'), ('9', 'Yorkshire'), ('10', 'Dalmata'), ('11', 'Boxer'), ('12', 'Bulldog ingles'), ('13', 'Bulldog Frances'), ('14', 'Beagle'), ('15', 'Dachshund'), ('16', 'Ns/Nc')], max_length=2, verbose_name='Raza')),
                ('sexo', models.CharField(choices=[('0', 'Hembra'), ('1', 'Macho'), ('2', 'Ns/Nc')], max_length=1, verbose_name='Sexo')),
                ('zona', models.CharField(blank=True, max_length=50, null=True)),
                ('comentario', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('dueño', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='perro_perdido',
        ),
    ]
