# Generated by Django 4.2 on 2023-05-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
        ('perdidaBusqueda', '0002_alter_perro_perdido_estado_alter_perro_perdido_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro_perdido',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='perro_perdido',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.raza'),
        ),
        migrations.AlterField(
            model_name='perro_perdido',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
