# Generated by Django 4.1.7 on 2023-06-27 00:47

from django.db import migrations, models
import perdidaBusqueda.models


class Migration(migrations.Migration):

    dependencies = [
        ('perdidaBusqueda', '0002_perroperdido_delete_perro_perdido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perroperdido',
            name='foto',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to=perdidaBusqueda.models.user_directory_path),
        ),
    ]
