# Generated by Django 4.1.7 on 2023-07-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdidaBusqueda', '0004_alter_perroperdido_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perroperdido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
