# Generated by Django 4.2 on 2023-07-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perdidaBusqueda', '0006_alter_perroperdido_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perroperdido',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perdidaBusqueda.zona'),
        ),
    ]
