# Generated by Django 4.1.7 on 2023-05-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='entrada_libreta_sanitaria',
            new_name='EntradaLibretaSanitaria',
        ),
        migrations.RenameModel(
            old_name='libreta_sanitaria',
            new_name='LibretaSanitaria',
        ),
    ]
