# Generated by Django 4.2 on 2023-05-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libreta_sanitaria',
            options={'verbose_name': 'libreta'},
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'verbose_name': 'mascota', 'verbose_name_plural': 'mascotas'},
        ),
    ]
