# Generated by Django 4.2 on 2023-05-06 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mascotas', '0002_alter_libreta_sanitaria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='dueño',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
