# Generated by Django 4.1.7 on 2023-05-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_rename_nacimiento_mascota_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(choices=[(0, 'Cruza')], max_length=1, verbose_name='Raza'),
        ),
    ]
