# Generated by Django 4.2 on 2023-05-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_alter_mascota_raza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(choices=[('0', 'Cruza'), ('1', 'Labrador')], max_length=1, verbose_name='Raza'),
        ),
    ]
