# Generated by Django 4.2 on 2023-05-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_alter_mascota_raza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradalibretasanitaria',
            name='libreta',
        ),
        migrations.AddField(
            model_name='entradalibretasanitaria',
            name='perro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota'),
        ),
        migrations.DeleteModel(
            name='LibretaSanitaria',
        ),
    ]
