# Generated by Django 4.1.7 on 2023-05-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0007_remove_entradalibretasanitaria_libreta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(choices=[('0', 'Cruza'), ('1', 'Labrador'), ('2', 'Rottweiler'), ('3', 'Pug'), ('4', 'Chihuahua'), ('5', 'Bulldog')], max_length=1, verbose_name='Raza'),
        ),
    ]
