# Generated by Django 4.1.7 on 2023-06-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0009_alter_entradalibretasanitaria_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradalibretasanitaria',
            old_name='perro',
            new_name='mascota',
        ),
        migrations.AlterField(
            model_name='entradalibretasanitaria',
            name='fecha',
            field=models.DateField(),
        ),
    ]
