# Generated by Django 4.1.7 on 2023-06-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0010_rename_perro_entradalibretasanitaria_mascota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradalibretasanitaria',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
