# Generated by Django 4.1.7 on 2023-06-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0012_alter_mascota_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradalibretasanitaria',
            old_name='mascota',
            new_name='perro',
        ),
    ]
