# Generated by Django 4.2 on 2023-06-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0013_rename_mascota_entradalibretasanitaria_perro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradalibretasanitaria',
            name='fecha',
            field=models.DateField(),
        ),
    ]
