# Generated by Django 4.2 on 2023-06-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0014_alter_entradalibretasanitaria_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradalibretasanitaria',
            name='cantidad_desparasitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
