# Generated by Django 4.2 on 2023-06-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0016_alter_entradalibretasanitaria_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(choices=[('0', 'Cruza'), ('1', 'Labrador'), ('2', 'Rottweiler'), ('3', 'Pug'), ('4', 'Chihuahua'), ('5', 'Husky Siberiano'), ('6', 'Golden'), ('7', 'Caniche'), ('8', 'Pastor Aleman'), ('9', 'Yorkshire'), ('10', 'Dalmata'), ('11', 'Boxer'), ('12', 'Bulldog ingles'), ('13', 'Bulldog Frances'), ('14', 'Beagle'), ('15', 'Dachshund'), ('16', 'Ns/Nc')], max_length=2, verbose_name='Raza'),
        ),
    ]
