# Generated by Django 4.2 on 2023-05-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perdidaBusqueda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(max_length=10)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactoPaseadoresCuidadores.rol')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perdidaBusqueda.zona')),
            ],
        ),
    ]
