# Generated by Django 4.2 on 2023-05-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactoPaseadoresCuidadores', '0002_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rol',
            field=models.CharField(choices=[('0', 'Paseador'), ('1', 'Cuidador')], max_length=1, verbose_name='Trabajo'),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
