# Generated by Django 4.2 on 2023-05-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactoPaseadoresCuidadores', '0003_alter_proveedor_rol_delete_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
