# Generated by Django 4.2 on 2023-05-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactoPaseadoresCuidadores', '0004_alter_proveedor_created_alter_proveedor_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
    ]
