# Generated by Django 4.2 on 2023-05-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactoPaseadoresCuidadores', '0005_alter_proveedor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='apellido',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
    ]
