# Generated by Django 4.2 on 2023-05-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='franja_horaria',
            new_name='franjaHoraria',
        ),
    ]
