# Generated by Django 4.2 on 2023-05-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_alter_mascota_raza'),
        ('turnos', '0002_rename_franja_horaria_turno_franjahoraria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota'),
        ),
    ]
