# Generated by Django 4.1.7 on 2023-05-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_alter_turno_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='motivo_rechazo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
