# Generated by Django 4.1.7 on 2023-05-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_turno_motivo_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('0', 'Pendiente'), ('1', 'Aceptado'), ('2', 'Rechazado'), ('3', 'Cancelado'), ('4', 'Cerrado')], max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.CharField(choices=[('0', 'Consulta General'), ('1', 'Vacuna A'), ('2', 'Vacuna B'), ('3', 'Desparasitacion'), ('4', 'Urgencia Intermedia'), ('5', 'Castracion')], max_length=15, verbose_name='Motivo'),
        ),
    ]
