# Generated by Django 4.2 on 2023-05-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_alter_turno_estado_alter_turno_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='monto',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='observaciones',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
