# Generated by Django 4.2 on 2023-05-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_turno_monto_turno_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
    ]
