# Generated by Django 4.2 on 2023-05-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0010_turno_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('0', 'Pendiente'), ('1', 'Aceptado'), ('2', 'Rechazado'), ('3', 'Cancelado'), ('4', 'Cerrado'), ('5', 'Vencido')], max_length=15, verbose_name='Estado'),
        ),
    ]
