# Generated by Django 4.2 on 2023-05-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0011_alter_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='hora',
            field=models.CharField(default='08:00', max_length=8, verbose_name='Horario'),
            preserve_default=False,
        ),
    ]
